# Generated by Django 3.0.7 on 2020-12-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201208_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
    ]
