# Generated by Django 3.0.7 on 2020-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='printposition',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='size',
        ),
        migrations.AddField(
            model_name='variants',
            name='category',
            field=models.CharField(choices=[('size', 'size'), ('colour', 'colour'), ('printposition', 'printposition')], default='colour', max_length=120),
        ),
        migrations.AddField(
            model_name='variants',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
