# Generated by Django 3.0.7 on 2020-12-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201208_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colour',
        ),
        migrations.DeleteModel(
            name='PrintPosition',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='variants',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
