# Generated by Django 3.0.7 on 2020-12-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201208_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variants',
            new_name='Variation',
        ),
    ]
