# Generated by Django 3.0.7 on 2020-12-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_variation_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
