# Generated by Django 3.0.7 on 2020-12-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_galleryimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimages',
            old_name='Image',
            new_name='image',
        ),
    ]
