# Generated by Django 3.0.7 on 2020-12-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201210_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimages',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='galleryimages',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
