# Generated by Django 3.0.7 on 2020-12-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20201231_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='colour',
            field=models.CharField(default='Not Chosen', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printposition',
            field=models.CharField(default='Not Chosen', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Not Chosen', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
    ]
